# Pandas Tutorial

### Grouping and Aggregation

In [1]:
import pandas as pd

data = {
    "Region": ["East", "East", "West", "West", "North"],
    "Category": ["Tech", "Furniture", "Tech", "Furniture", "Tech"],
    "Month": ["Jan", "Jan", "Feb", "Feb", "Jan"],
    "Sales": [500, 300, 700, 200, 400]
}

df = pd.DataFrame(data)

In [2]:
df.groupby("Region")["Sales"].sum()

Region
East     800
North    400
West     900
Name: Sales, dtype: int64

In [5]:
df.groupby(["Region", "Category"])["Sales"].sum()

Region  Category
East    Furniture    300
        Tech         500
North   Tech         400
West    Furniture    200
        Tech         700
Name: Sales, dtype: int64

In [6]:
df.groupby("Category")["Sales"].mean()

Category
Furniture    250.000000
Tech         533.333333
Name: Sales, dtype: float64

In [7]:
df.groupby("Region").agg({
    "Sales": ["sum", "mean"],
})

       Sales
         sum   mean
Region
East     800  400.0
North    400  400.0
West     900  450.0

In [8]:
df.pivot_table(
    values="Sales",
    index="Region",
    columns="Category",
    aggfunc="sum"
)

Category  Furniture   Tech
Region
East          300.0  500.0
North           NaN  400.0
West          200.0  700.0