# Pandas Tutorial

### Pandas Basics

#### Series

In [36]:
import pandas as pd

x = pd.Series([10, 20, 30, 40, 50]) # List

In [37]:
y = pd.Series([1, 2, 3, 4, 5], index=['a', 'b', 'c', 'd', 'e']) # Custom Index

In [38]:
z = pd.Series({'a': 1, 'b': 2, 'c': 3}) # Dictionary

In [39]:
x[:2] # Slicing

0    10
1    20
dtype: int64

In [40]:
y + 5 # Operations

a     6
b     7
c     8
d     9
e    10
dtype: int64

In [41]:
print("Index of x:", x.index)
print("Index of y:", y.index)

Index of x: RangeIndex(start=0, stop=5, step=1)
Index of y: Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [42]:
x.values

array([10, 20, 30, 40, 50])

In [43]:
y.dtype

dtype('int64')

#### Dataframe

In [44]:
data = {
    "Name": ["Aarav", "Sita", "Rohan"],
    "Age": [20, 21, 19],
    "Marks": [85, 90, 78]
}

df = pd.DataFrame(data)
print(df)

    Name  Age  Marks
0  Aarav   20     85
1   Sita   21     90
2  Rohan   19     78

In [45]:
df["Name"]
df[["Name", "Marks"]]

    Name  Marks
0  Aarav     85
1   Sita     90
2  Rohan     78

In [46]:
df.loc[0] # Label Based
df.iloc[0] # Position Based

Name     Aarav
Age         20
Marks       85
Name: 0, dtype: object

In [47]:
df["Marks"].mean()

np.float64(84.33333333333333)

In [48]:
print(df.shape)
print(df.columns)
print(df.index)
print(df.dtypes)

(3, 3)
Index(['Name', 'Age', 'Marks'], dtype='object')
RangeIndex(start=0, stop=3, step=1)
Name     object
Age       int64
Marks     int64
dtype: object

#### Data Loading

In [49]:
df = pd.read_csv("amazon.csv")
# df = pd.read_excel("amazon.xlsx")

df.head()
df.tail()

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content,img_link,product_link
1460,B08L7J3T31,Noir Aqua - 5pcs PP Spun Filter + 1 Spanner | ...,Home&Kitchen|Kitchen&HomeAppliances|WaterPurif...,₹379,₹919,59%,4,"1,090",SUPREME QUALITY 90 GRAM 3 LAYER THIK PP SPUN F...,"AHITFY6AHALOFOHOZEOC6XBP4FEA,AFRABBODZJZQB6Z4U...","Prabha ds,Raghuram bk,Real Deal,Amazon Custome...","R3G3XFHPBFF0E8,R3C0BZCD32EIGW,R2EBVBCN9QPD9R,R...","Received the product without spanner,Excellent...","I received product without spanner,Excellent p...",https://m.media-amazon.com/images/I/41fDdRtjfx...,https://www.amazon.in/Noir-Aqua-Spanner-Purifi...
1461,B01M6453MB,Prestige Delight PRWO Electric Rice Cooker (1 ...,Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...,"₹2,280","₹3,045",25%,4.1,"4,118","230 Volts, 400 watts, 1 Year","AFG5FM3NEMOL6BNFRV2NK5FNJCHQ,AGEINTRN6Z563RMLH...","Manu Bhai,Naveenpittu,Evatira Sangma,JAGANNADH...","R3DDL2UPKQ2CK9,R2SYYU1OATVIU5,R1VM993161IYRW,R...","ok,everything was good couldn't return bcoz I ...","ok,got everything as mentioned but the measuri...",https://m.media-amazon.com/images/I/41gzDxk4+k...,https://www.amazon.in/Prestige-Delight-PRWO-1-...
1462,B009P2LIL4,Bajaj Majesty RX10 2000 Watts Heat Convector R...,"Home&Kitchen|Heating,Cooling&AirQuality|RoomHe...","₹2,219","₹3,080",28%,3.6,468,International design and styling|Two heat sett...,"AGVPWCMAHYQWJOQKMUJN4DW3KM5Q,AF4Q3E66MY4SR7YQZ...","Nehal Desai,Danish Parwez,Amazon Customer,Amaz...","R1TLRJVW4STY5I,R2O455KRN493R1,R3Q5MVGBRIAS2G,R...","very good,Work but front melt after 2 month,Go...","plastic but cool body ,u have to find sturdy s...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Bajaj-RX-10-2000-Watt-Co...
1463,B00J5DYCCA,Havells Ventil Air DSP 230mm Exhaust Fan (Pist...,"Home&Kitchen|Heating,Cooling&AirQuality|Fans|E...","₹1,399","₹1,890",26%,4,"8,031",Fan sweep area: 230 MM ; Noise level: (40 - 45...,"AF2JQCLSCY3QJATWUNNHUSVUPNQQ,AFDMLUXC5LS5RXDJS...","Shubham Dubey,E.GURUBARAN,Mayank S.,eusuf khan...","R39Q2Y79MM9SWK,R3079BG1NIH6MB,R29A31ZELTZNJM,R...","Fan Speed is slow,Good quality,Good product,go...",I have installed this in my kitchen working fi...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Havells-Ventilair-230mm-...
1464,B01486F4G6,Borosil Jumbo 1000-Watt Grill Sandwich Maker (...,Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...,"₹2,863","₹3,690",22%,4.3,"6,987","Brand-Borosil, Specification â€“ 23V ~ 5Hz;1 W...","AFGW5PT3R6ZAVQR4Y5MWVAKBZAYA,AG7QNJ2SCS5VS5VYY...","Rajib,Ajay B,Vikas Kahol,PARDEEP,Anindya Prama...","R20RBRZ0WEUJT9,ROKIFK9R2ISSE,R30EEG2FNJSN5I,R2...","Works perfect,Ok good product,Nice Product. Re...",It does it job perfectly..only issue is temp c...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Borosil-Jumbo-1000-Watt-...

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1465 entries, 0 to 1464
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   product_id           1465 non-null   object
 1   product_name         1465 non-null   object
 2   category             1465 non-null   object
 3   discounted_price     1465 non-null   object
 4   actual_price         1465 non-null   object
 5   discount_percentage  1465 non-null   object
 6   rating               1465 non-null   object
 7   rating_count         1463 non-null   object
 8   about_product        1465 non-null   object
 9   user_id              1465 non-null   object
 10  user_name            1465 non-null   object
 11  review_id            1465 non-null   object
 12  review_title         1465 non-null   object
 13  review_content       1465 non-null   object
 14  img_link             1465 non-null   object
 15  product_link         1465 non-null   object
dtypes: object(16)
memory usage: 183.3+ KB

In [51]:
df["actual_price"].describe()

count     1465
unique     449
top       ₹999
freq       120
Name: actual_price, dtype: object

In [ ]:
df[["product_name", "discounted_price"]]

In [ ]:
df["actual_price"] = df["actual_price"].str.replace("₹", "", regex=False)
df["actual_price"] = df["actual_price"].str.replace(",", "", regex=False)

df["actual_price"] = pd.to_numeric(df["actual_price"])
df[df["actual_price"] > 2000]

In [54]:
df["actual_price"].dtype

dtype('float64')

In [ ]:
df.sort_values("actual_price", ascending=False)

#### Missing Values

In [ ]:
df["rating_count "].isnull().sum()

np.int64(2)

In [ ]:
df.dropna(thresh=2)  # Keeps rows with at least 2 non-null values
df.dropna(how="all") # Drop only if all values are missing
df.dropna(axis=1)

In [ ]:
df.fillna(0) # Fill with a constant value

In [ ]:
# df["rating_count"].fillna(df["rating_count"].mean())

In [ ]:
df.fillna(method="ffill") # Fill with forward value
df.fillna(method="bfill") # Fill with backward value